name: Script Runner with Timestamp (Artifact Storage)

on: [push]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Timestamp Artifact
        uses: actions/download-artifact@v4
        with:
          name: timestamp
          path: artifacts/
        continue-on-error: true
        id: download_timestamp

      - name: Read Timestamp
        id: get_timestamp
        run: |
          echo "timestamp=$(cat artifacts/timestamp || echo 'none')" >> $GITHUB_OUTPUT

      - name: Run Script with Timestamp
        run: |
          if [ "${{ steps.get_timestamp.outputs.timestamp }}" = "none" ]; then
            echo "No previous timestamp found."
            mkdir artifacts
            sha1sum <<< "yolo"
          else
            echo "Previous timestamp: ${{ steps.get_timestamp.outputs.timestamp }}"
            sha1sum <<< "${{ steps.get_timestamp.outputs.timestamp }}"
          fi
          
          echo "$(date +%s)" > artifacts/timestamp

      - name: Upload Timestamp Artifact
        uses: actions/upload-artifact@v4
        with:
          name: timestamp
          path: artifacts/
